extensions:
  basecom.cron-ui.create-modal.cronjob:
    module: custom_entity/form/creation/modal
    config:
      labels:
        title:    'pim_custom_entity.create_popin.title'
        subTitle: 'basecom.cron-ui.cronjobs' # TODO: Validate
      picture:        'illustrations/User.svg' # Custom logo / image
      successMessage: 'pim_custom_entity.message.created' # TODO: Custom translation file
      editRoute:      'pim_customentity_rest_get'
      routerKey:      'code'
      postUrl:
        route: 'pim_customentity_rest_create'
        parameters:
          customEntityName: 'cronjob'

  basecom.cron-ui.create-modal.cronjob.code:
    module:     'pim/form/common/creation/field'
    parent:     'basecom.cron-ui.create-modal.cronjob'
    targetZone: 'fields'
    position:   10
    config:
      identifier: 'code'
      label:      'Code' # TODO: Translation file

  basecom.cron-ui.create-modal.cronjob.command:
    module:     'pim/form/common/creation/field'
    parent:     'basecom.cron-ui.create-modal.cronjob'
    targetZone: 'fields'
    position:   20
    config:
      identifier: 'command'
      label:      'Command' # TODO: Translation file

  basecom.cron-ui.create-modal.cronjob.expression:
    module:     'pim/form/common/creation/field'
    parent:     'basecom.cron-ui.create-modal.cronjob'
    targetZone: 'fields'
    position:   30
    config:
      identifier: 'expression'
      label:      'Expression' # TODO: Translation file

  # TODO: backgroundTask checkbox