extensions:
  basecom.cron-ui.create-modal.cronjob:
    module: 'custom_entity/form/creation/modal'
    config:
      labels:
        title:    'pim_custom_entity.create_popin.title'
        subTitle: 'basecom.cron-ui.cronjobs'
      picture:        '../../basecomcronui/images/illustrations/logo_110.png' # Custom logo / image
      successMessage: 'basecom.cron-ui.messages.created'
      editRoute:      'pim_customentity_rest_get'
      routerKey:      'code'
      postUrl:
        route: 'pim_customentity_rest_create'
        parameters:
          customEntityName: 'cronjob'

  basecom.cron-ui.create-modal.cronjob.code:
    module:     'pim/form/common/creation/field'
    parent:     'basecom.cron-ui.create-modal.cronjob'
    targetZone: 'fields'
    position:   10
    config:
      identifier: 'code'
      label:      'basecom.cron-ui.fields.code'

  basecom.cron-ui.create-modal.cronjob.command:
    module:     'pim/form/common/creation/field'
    parent:     'basecom.cron-ui.create-modal.cronjob'
    targetZone: 'fields'
    position:   20
    config:
      identifier: 'command'
      label:      'basecom.cron-ui.fields.command'
