datagrid:
  cronjob:
    options:
      entityHint:    'cronjob'
      manageFilters: false
    source:
      type:              'pim_datasource_default'
      entity:            '%basecom.cron-ui.entity.cronjob.class%'
      repository_method: 'createDatagridQueryBuilder'
    columns:
      code:
        label: 'Code'
      command:
        label: 'Command'
      expression:
        label: 'Cron Expression'
      backgroundTask:
        label:         'Run in background?'
        frontend_type: 'boolean-status'
    properties:
      id: ~
      edit_link:
        type:  'url'
        route: 'pim_customentity_rest_get'
        params:
        - id
        - customEntityName
      delete_link:
        type:  'url'
        route: 'pim_customentity_rest_delete'
        params:
        - id
        - customEntityName
    actions:
      edit:
        type:         'navigate'
        acl_resource: 'basecom.cron-ui.edit.cronjob'
        label:        'Edit the cronjob'
        icon:         'edit'
        link:         'edit_link'
        rowAction:    true
      delete:
        type:         'delete'
        acl_resource: 'basecom.cron-ui.delete.cronjob'
        label:        'Delete the cronjob'
        icon:         'trash'
        link:         'delete_link'
    sorters:
      columns:
        code:
          data_name: 'rd.code'
        command:
          data_name: 'rd.command'
      default:
        code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
    filters:
      columns:
        command:
          type:      'search'
          label:     'Command' # Translation file
          data_name: 'rd.command'
        code:
          type:      'string'
          label:     'Code' # Translation file
          data_name: 'rd.code'
        expression:
          type:      'string'
          label:     'Expression' # Translation file
          data_name: 'rd.expression'
        backgroundTask:
          type:      'boolean'
          label:     'Run in background?'
          data_name: 'rd.backgroundTask'
    mass_actions:
      delete:
        type:         'delete'
        label:        'pim.grid.mass_action.delete'
        entity_name:  'cronjob'
        acl_resource: ~
        handler:      'mass_delete'
        className:    'AknButton AknButton--important AknButtonList-item'
        messages:
          confirm_title:   'pim_datagrid.mass_action.delete.confirm_title'
          confirm_content: 'Are you sure you want to delete all selected cronjobs?'
          confirm_ok:      'pim_datagrid.mass_action.delete.confirm_ok'
          success:         'The selected cronjobs were successfully deleted.'
          error:           'pim_datagrid.mass_action.delete.error'
          empty_selection: 'pim_datagrid.mass_action.delete.empty_selection'
