basecom.cron-ui.index.cronjob:
  type:       'action'
  label:      'Cronjob' # TODO: Custom trans file
  group_name: 'pim_custom_entity.acl_group.reference_data'

basecom.cron-ui.create.cronjob:
  type:       'action'
  label:      'create' # TODO: trans file
  group_name: pim_custom_entity.acl_group.reference_data

basecom.cron-ui.edit.cronjob:
  type:       'action'
  label:      'edit' # TODO: trans file
  group_name: pim_custom_entity.acl_group.reference_data

basecom.cron-ui.delete.cronjob:
  type:       'action'
  label:      'delete' # TODO: trans file
  group_name: pim_custom_entity.acl_group.reference_data
