parameters:
  basecom.cron-ui.builder.cronjob.class: 'Basecom\Bundle\CronUiBundle\Builder\CronjobBuilder'

services:
  basecom.cron-ui.builder.cronjob:
    class: '%basecom.cron-ui.builder.cronjob.class%'
    arguments:
      - '@basecom.cron-ui.repository.cronjob'
      - '%kernel.root_dir%'